name: Deploy to prod

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]

jobs:
  Deploy-to-prod:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test --if-present
      - run: npm run build --if-present
