name: Deploy to prod

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]

jobs:
  Deploy-to-prod:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set-up Node.js ${{ matrix.node-version }} and build 🔧
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run test --if-present
          npm run build --if-present
      - name: Deploy to prod  🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
